import Link from 'next/link';
import Head from 'next/head';
import { FaLanguage, FaBook, FaGlobe, FaHistory, FaBrain, FaCalculator, FaFlask, FaMicroscope, FaReact } from 'react-icons/fa';
import { AiOutlineStock } from "react-icons/ai";
import { RiEnglishInput } from "react-icons/ri";
import { GrLanguage } from "react-icons/gr";
import { GiThink } from "react-icons/gi";

const ButtonLink = ({ href, subjectName, icon: Icon, children }) => (
  <Link href={{ pathname: href, query: { subject: subjectName } }} legacyBehavior>
    <a className="flex items-center text-lg border border-black rounded-lg px-4 py-2 hover:bg-black hover:text-white transition-colors duration-300 mx-2 my-2">
      <Icon className="mr-2" />
      {children}
    </a>
  </Link>
);

const categories = [
  {
    title: 'STEM',
    subjects: [
      { name: 'Biology', href: '/Topic', icon: FaMicroscope },
      { name: 'Chemistry', href: '/Topic', icon: FaFlask },
      { name: 'Mathematics', href: '/Topic', icon: FaCalculator },
      { name: 'Physics', href: '/Topic', icon: FaReact },
    ],
  },  
  {
    title: 'Humanities',
    subjects: [
      { name: 'Business', href: '/Topic', icon: FaBook },
      { name: 'Economics', href: '/Topic', icon: AiOutlineStock },
      { name: 'Geography', href: '/Topic', icon: FaGlobe },
      { name: 'History', href: '/Topic', icon: FaHistory },
      { name: 'Philosophy', href: '/Topic', icon: GiThink },
      { name: 'Psychology', href: '/Topic', icon: FaBrain },
    ],
  },  
  {
    title: 'Languages',
    subjects: [
      { name: 'Chinese', href: '/Topic', icon: FaLanguage },
      { name: 'English', href: '/Topic', icon: RiEnglishInput },
      { name: 'French', href: '/Topic', icon: GrLanguage },
    ],
  },
];

export default function Schedule() {
  return (
    <div className="min-h-screen flex flex-col items-center justify-center text-gray-800">
      <Head>
        <title>Spacey</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
        <link rel="manifest" href="/site.webmanifest" />
        <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5" />
        <meta name="msapplication-TileColor" content="#da532c" />
        <meta name="theme-color" content="#ffffff" />
      </Head>

      <div className="w-full max-w-6xl mx-auto px-4 mb-60 text-center">
        <div className="mb-12">
          <h1 className="text-5xl font-bold mt-10 mb-3 text-black">Topic</h1>
          <p className="text-xl mb-10 text-black">Make Your Choice!</p>
        </div>
        <div className="flex flex-wrap justify-center">
          {categories.map((category, index) => (
            <div key={index} className="bg-white border border-gray-300 rounded-lg shadow-lg p-6 m-4 max-w-xs w-full">
              <h1 className="text-3xl font-bold mb-4 text-black text-center">{category.title}</h1>
              <div className="flex flex-wrap justify-center">
                {category.subjects.map((subject, subIndex) => (
                  <ButtonLink key={subIndex} href={subject.href} subjectName={subject.name} icon={subject.icon}>
                    {subject.name}
                  </ButtonLink>
                ))}
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
